const App={
 view:"dashboard", selectedDate:isoToday(),
 init(){
  Settings.applyTheme();this.bindNav();this.renderView("dashboard");
  document.getElementById("quickFab").onclick=()=>this.openReport(isoToday(),true);
  document.getElementById("menuBtn").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
  document.getElementById("themeBtn").onclick=()=>{const s=Store.getSettings();s.theme=s.theme==="dark"?"light":s.theme==="light"?"system":"dark";Store.saveSettings(s);Settings.applyTheme();this.toast(`Theme: ${s.theme}`)};
  document.getElementById("todayBtn").onclick=()=>this.openReport(isoToday());
  setTimeout(async()=>{const mode=localStorage.getItem("dutylog_auto_backup")||"off";const last=+new Date(localStorage.getItem("dutylog_last_backup")||0);const due=mode==="daily"?Date.now()-last>86400000:mode==="6h"?Date.now()-last>21600000:false;if(due&&localStorage.getItem("dutylog_drive_connected")==="1"){try{await DriveSync.backup();this.toast("Automatic cloud backup completed.")}catch{}}},1200);
 },
 bindNav(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{this.renderView(b.dataset.view);document.getElementById("sidebar").classList.remove("open")})},
 title(v){const map={dashboard:["Overview","Dashboard"],calendar:["Planning","Calendar"],reports:["Archive","Daily Reports"],generator:["Workspace","Report Generator"],monthly:["Reporting","Monthly Reports"],analytics:["Insights","Analytics"],leave:["Records","Holidays & Leave"],settings:["Configuration","Settings"]};document.getElementById("viewKicker").textContent=map[v][0];document.getElementById("viewTitle").textContent=map[v][1]},
 renderView(v){this.view=v;this.title(v);const m=document.getElementById("main");m.innerHTML=`<div class="page"><div class="empty">Loading workspace…</div></div>`;setTimeout(()=>{if(v==="dashboard")this.dashboard(m);if(v==="calendar")this.calendarPage(m);if(v==="reports")this.reportsPage(m);if(v==="generator")this.generator(m);if(v==="monthly")this.monthly(m);if(v==="analytics")this.analyticsPage(m);if(v==="leave")this.leavePage(m);if(v==="settings"){m.innerHTML=Settings.html();this.bindSettings()}},0)},
 dashboard(m){
  const rs=Store.getReports(),now=new Date(),st=Analytics.stats(rs,now.getFullYear(),now.getMonth()),today=rs.find(r=>r.date===isoToday()),s=Store.getSettings();
  const working=rs.filter(r=>r.status==="Working Day").length,hol=rs.filter(r=>r.status==="Holiday").length,leave=rs.filter(r=>r.status==="Leave").length,complete=rs.filter(r=>r.status==="Working Day"&&r.generatedReport).length,pct=working?Math.round(complete/working*100):0;
  const recent=rs.slice(-5).reverse();
  m.innerHTML=`<div class="page"><div class="hero"><div class="hero-card"><div class="eyebrow" style="color:#b9c8ef">Your duty record, organized.</div><h2>Good ${new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, ${esc(s.name.split(" ")[0])}.</h2><p>Turn quick notes into professional institutional reports. Everything you did, clearly documented.</p><div class="actions"><button class="btn gold" id="heroQuick">✦ Quick report</button><button class="btn" style="background:rgba(255,255,255,.12);color:#fff;border-color:rgba(255,255,255,.2)" id="heroCalendar">Open calendar</button></div></div><div class="today-card"><div class="eyebrow">Today</div><div class="today-date">${fmtDate(isoToday())}</div><div class="muted" style="font-size:11px">${dayName(isoToday())}</div><div style="margin-top:17px">${today?`<span class="pill ${today.status==="Leave"?"danger":today.generatedReport?"success":"warning"}">${today.status==="Working Day"?(today.generatedReport?"Report completed":"Report pending"):today.status}</span>`:`<span class="pill warning">Report pending</span>`}</div><button class="btn primary" style="margin-top:15px;width:100%" id="todayReport">Open today's report</button></div></div>
  <div class="grid stats"><div class="stat"><div class="stat-label">Working Days</div><div class="stat-value">${working}</div><div class="stat-foot">All recorded periods</div></div><div class="stat"><div class="stat-label">Reports</div><div class="stat-value">${complete}</div><div class="stat-foot">${working-complete} pending</div></div><div class="stat"><div class="stat-label">Holidays</div><div class="stat-value">${hol}</div><div class="stat-foot">Recorded holidays</div></div><div class="stat"><div class="stat-label">Leave</div><div class="stat-value">${leave}</div><div class="stat-foot">Recorded leave days</div></div></div>
  <div class="grid quick-grid" style="margin-top:15px">${[["✦","New Daily Report","Create today's record","quickNew"],["▦","Open Calendar","Browse every date","quickCal"],["▣","Monthly Report","Generate a month","quickMonth"],["⇩","Backup Data","Protect your archive","quickBackup"]].map(x=>`<button class="quick" id="${x[3]}"><span class="qicon">${x[0]}</span><span><b>${x[1]}</b><small>${x[2]}</small></span></button>`).join("")}</div>
  <div class="grid two-col" style="margin-top:15px"><div class="section"><div class="section-title"><h3>Report completion</h3><span>${pct}%</span></div><div class="progress"><span style="width:${pct}%"></span></div><p class="muted" style="font-size:11px">${complete} of ${working} recorded working days have completed reports.</p></div><div class="section"><div class="section-title"><h3>Current streak</h3><span>Consecutive</span></div><div style="font:800 32px var(--display)">${Analytics.streak()} <span style="font-size:12px;color:var(--muted)">days</span></div><div class="muted" style="font-size:11px">Completed daily reports</div></div></div>
  <div class="section" style="margin-top:15px"><div class="section-title"><h3>Recent activity</h3><button class="btn ghost" id="seeReports">View all</button></div>${recent.length?recent.map(r=>`<div class="report-row"><div><b style="font-size:12px">${fmtDate(r.date)}</b><div class="muted" style="font-size:10px">${r.status==="Working Day"?(r.generatedReport?"Daily Duty Report":"Pending report"):r.status}</div></div><span class="pill ${r.status==="Leave"?"danger":r.status==="Holiday"?"warning":r.generatedReport?"success":"info"}>${r.status==="Working Day"?(r.generatedReport?"Completed":"Pending"):r.status}</span></div>`).join(""):`<div class="empty"><strong>No duty reports recorded yet.</strong>Create your first report to begin.</div>`}</div></div>`;
  [["heroQuick",()=>this.openReport(isoToday(),true)],["heroCalendar",()=>this.renderView("calendar")],["todayReport",()=>this.openReport(isoToday())],["quickNew",()=>this.openReport(isoToday(),true)],["quickCal",()=>this.renderView("calendar")],["quickMonth",()=>this.renderView("monthly")],["quickBackup",()=>Exporter.json()],["seeReports",()=>this.renderView("reports")]].forEach(([id,fn])=>document.getElementById(id)?.addEventListener("click",fn))
 },
 calendarPage(m){m.innerHTML=`<div class="page"><div class="page-head"><div><div class="eyebrow">Planning</div><h1>Calendar</h1><p class="page-sub">See your working days, holidays, leave and report completion at a glance.</p></div><button class="btn primary" id="calQuick">+ Quick report</button></div><div id="calendarMount"></div></div>`;Calendar.render(document.getElementById("calendarMount"));document.getElementById("calQuick").onclick=()=>this.openReport(isoToday(),true)},
 reportsPage(m){m.innerHTML=`<div class="page"><div class="page-head"><div><div class="eyebrow">Archive</div><h1>Daily Reports</h1><p class="page-sub">Search and manage your complete duty journal.</p></div><button class="btn primary" id="reportNew">+ New report</button></div><div class="section"><div class="form-grid"><div class="field"><label>Search reports</label><input id="reportSearch" class="input" placeholder="Search library, attendance, meetings…"></div><div class="field"><label>Status</label><select id="reportStatus" class="select"><option>All</option><option>Working Day</option><option>Holiday</option><option>Leave</option></select></div></div><div id="reportList" style="margin-top:12px"></div></div></div>`;const draw=()=>{const a=Reports.filter(document.getElementById("reportSearch").value,document.getElementById("reportStatus").value),box=document.getElementById("reportList");box.innerHTML=a.length?a.map(r=>`<div class="report-row"><div style="min-width:0"><b style="font-size:12px">${fmtDate(r.date)}</b><div class="muted" style="font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:520px">${esc(r.generatedReport||r.notes||r.holidayName||r.leaveReason||"No details")}</div><div class="muted" style="font-size:9px">${(r.generatedReport||"").split(/\s+/).filter(Boolean).length} words • Updated ${new Date(r.updatedAt).toLocaleDateString("en-IN")}</div></div><div class="actions"><span class="pill ${r.status==="Leave"?"danger":r.status==="Holiday"?"warning":r.generatedReport?"success":"info"}>${r.status==="Working Day"?(r.generatedReport?"Completed":"Pending"):r.status}</span><button class="btn" data-open="${r.date}">View</button></div></div>`).join(""):`<div class="empty"><strong>No matching reports.</strong>Try another search or create a new report.</div>`;box.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>this.openReport(b.dataset.open))};document.getElementById("reportSearch").oninput=draw;document.getElementById("reportStatus").onchange=draw;document.getElementById("reportNew").onclick=()=>this.openReport(isoToday(),true);draw()},
 generator(m){this.openReport(isoToday(),true)},
 monthly(m){const now=new Date(),prefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;m.innerHTML=`<div class="page"><div class="page-head"><div><div class="eyebrow">Reporting</div><h1>Monthly Reports</h1><p class="page-sub">Build a polished monthly institutional duty record.</p></div></div><div class="section"><div class="form-grid"><div class="field"><label>Month</label><input type="month" class="input" id="monthPick" value="${prefix}"></div><div class="field" style="align-content:end"><button class="btn primary" id="generateMonth">Generate Monthly Preview</button></div></div></div><div id="monthOut" style="margin-top:15px"></div></div>`;document.getElementById("generateMonth").onclick=()=>this.renderMonth(document.getElementById("monthPick").value);this.renderMonth(prefix)},
 renderMonth(val){const [y,m]=val.split("-").map(Number),a=Store.getReports().filter(r=>r.date.startsWith(val)).sort((a,b)=>a.date.localeCompare(b.date)),st=Analytics.stats(Store.getReports(),y,m-1),s=Store.getSettings();document.getElementById("monthOut").innerHTML=`<div class="report-paper"><div class="inst">${esc(s.institution).toUpperCase()}</div><div class="report-title">DUTY & WORK REPORT</div><div style="text-align:center;color:#667085;font-size:11px;margin-bottom:30px">${monthName(y,m-1)}<br><br><b>Submitted by</b><br>${esc(s.name)}<br><br><b>Submitted to</b><br>${esc(s.authority)}</div><div class="report-meta"><div><b>Working Days:</b> ${st.working}</div><div><b>Reports Submitted:</b> ${st.completed}</div><div><b>Holidays:</b> ${st.holiday}</div><div><b>Leave:</b> ${st.leave}</div><div><b>Completion:</b> ${st.completion}%</div></div><h4>MONTH AT A GLANCE</h4><p>This report consolidates the duty and work records recorded for ${monthName(y,m-1)}. The summary below is based only on the entries saved in DUTYLOG AI.</p><h4>DAY-WISE REPORT</h4>${a.length?a.map(r=>`<div style="padding:10px 0;border-bottom:1px solid #e5e7eb"><b style="font-size:11px">${fmtDate(r.date)}</b> <span style="font-size:9px;color:#667085">${r.status}</span><p style="margin:5px 0;font-size:11px;line-height:1.7">${esc(r.generatedReport||r.notes||r.holidayName||r.leaveReason||"No report content.")}</p></div>`).join(""):`<p>No records for this month.</p>`}</div>`},
 analyticsPage(m){const rs=Store.getReports(),now=new Date(),st=Analytics.stats(rs,now.getFullYear(),now.getMonth()),cats=Analytics.categories(),max=Math.max(1,...Object.values(cats));m.innerHTML=`<div class="page"><div class="page-head"><div><div class="eyebrow">Insights</div><h1>Analytics</h1><p class="page-sub">Simple signals from your recorded institutional work.</p></div></div><div class="grid stats"><div class="stat"><div class="stat-label">This Month Working</div><div class="stat-value">${st.working}</div></div><div class="stat"><div class="stat-label">Reports Submitted</div><div class="stat-value">${st.completed}</div></div><div class="stat"><div class="stat-label">Completion</div><div class="stat-value">${st.completion}%</div></div><div class="stat"><div class="stat-label">Streak</div><div class="stat-value">${Analytics.streak()}</div></div></div><div class="grid two-col" style="margin-top:15px"><div class="section"><div class="section-title"><h3>Activity categories</h3><span>All records</span></div>${Object.keys(cats).length?Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div style="display:grid;grid-template-columns:120px 1fr 30px;gap:8px;align-items:center;margin:11px 0;font-size:10px"><span>${k}</span><div class="progress"><span style="width:${v/max*100}%"></span></div><b>${v}</b></div>`).join(""):`<div class="empty">Add activity tags to see category analytics.</div>`}</div><div class="section"><div class="section-title"><h3>Status distribution</h3></div>${[["Working Day",st.working,"success"],["Holiday",st.holiday,"warning"],["Leave",st.leave,"danger"]].map(x=>`<div class="activity-row"><span>${x[0]}</span><span class="pill ${x[2]}">${x[1]}</span></div>`).join("")}</div></div></div>`},
 leavePage(m){const a=Store.getReports().filter(r=>r.status!=="Working Day").sort((a,b)=>b.date.localeCompare(a.date));m.innerHTML=`<div class="page"><div class="page-head"><div><div class="eyebrow">Records</div><h1>Holidays & Leave</h1><p class="page-sub">Manage non-working days in the duty calendar.</p></div><button class="btn primary" id="addSpecial">+ Add record</button></div><div class="section">${a.length?a.map(r=>`<div class="report-row"><div><b>${fmtDate(r.date)}</b><div class="muted" style="font-size:10px">${r.status==="Holiday"?r.holidayName:r.leaveType} · ${r.status==="Holiday"?(r.holidayDescription||""):(r.leaveReason||"")}</div></div><button class="btn" data-special="${r.date}">Edit</button></div>`).join(""):`<div class="empty"><strong>No holidays or leave recorded.</strong>Add a non-working day to keep your monthly record accurate.</div>`}</div></div>`;document.getElementById("addSpecial").onclick=()=>this.openReport(isoToday(),true,"Holiday");m.querySelectorAll("[data-special]").forEach(b=>b.onclick=()=>this.openReport(b.dataset.special))},
 bindSettings(){document.getElementById("settingsForm").onsubmit=e=>{e.preventDefault();Settings.saveFromForm(e.target)};document.getElementById("exportJson").onclick=()=>Exporter.json();document.getElementById("exportCsv").onclick=()=>Exporter.csv();document.getElementById("importJson").onclick=()=>{const i=document.createElement("input");i.type="file";i.accept=".json";i.onchange=async()=>{try{const obj=JSON.parse(await i.files[0].text());const replace=confirm("Replace existing reports with this backup?\nOK = Replace\nCancel = Merge");Store.importJSON(obj,replace);Settings.applyTheme();this.toast("Backup imported successfully.");this.renderView("dashboard")}catch(e){this.toast("Invalid or corrupted backup.","error")}};i.click()};document.getElementById("clearData").onclick=()=>{if(confirm("This permanently clears all DUTYLOG reports. Continue?")&&confirm("Final confirmation: delete all saved records?")){Store.saveReports([]);this.toast("All report data cleared.");this.renderView("dashboard")}};
 const ac=document.getElementById("autoBackup");ac.value=localStorage.getItem("dutylog_auto_backup")||"off";ac.onchange=()=>localStorage.setItem("dutylog_auto_backup",ac.value);
 document.getElementById("googleClientId").onchange=e=>localStorage.setItem("dutylog_google_client_id",e.target.value.trim());
 document.getElementById("connectDrive").onclick=async()=>{try{localStorage.setItem("dutylog_google_client_id",document.getElementById("googleClientId").value.trim());await DriveSync.connect();await DriveSync.refreshMeta();this.toast("Google Drive connected.")}catch(e){this.toast(e.message||"Google Drive connection failed.","error")}};
 document.getElementById("backupDrive").onclick=async()=>{try{await DriveSync.backup();await DriveSync.refreshMeta();this.toast("Cloud backup completed.")}catch(e){this.toast(e.message||"Backup failed.","error")}};
 document.getElementById("restoreDrive").onclick=async()=>{try{const r=await DriveSync.sync();await DriveSync.refreshMeta();this.toast(r.mode==="restored"?"Cloud data restored.":"Cloud and device data merged.");this.renderView("dashboard")}catch(e){this.toast(e.message||"Sync failed.","error")}};
 document.getElementById("disconnectDrive").onclick=()=>{DriveSync.disconnect();this.toast("Google Drive disconnected.")};
 DriveSync.refreshMeta();},
 openReport(date,quick=false,forcedStatus=null){const existing=Store.getReports().find(r=>r.date===date),r=existing||{date,day:dayName(date),status:forcedStatus||"Working Day",notes:"",generatedReport:"",activities:[],remarks:"",holidayName:"",holidayDescription:"",leaveType:"Personal Leave",leaveReason:"",tags:[]};this.selectedDate=date;this.showModal(this.reportForm(r,quick))},
 reportForm(r,quick){const tags=Reports.activityTags;return `<div><button class="icon-btn modal-close" id="modalClose">×</button><div class="eyebrow">Daily journal</div><h2 style="font:800 22px var(--display);margin:5px 0 2px">${fmtDate(r.date)}</h2><p class="muted" style="font-size:11px">${r.day||dayName(r.date)}</p><div class="grid" style="gap:14px;margin-top:17px"><div class="field"><label>Status</label><div class="actions"><button class="btn statusBtn ${r.status==="Working Day"?"primary":""}" data-status="Working Day">Working Day</button><button class="btn statusBtn ${r.status==="Holiday"?"gold":""}" data-status="Holiday">Holiday</button><button class="btn statusBtn ${r.status==="Leave"?"danger":""}" data-status="Leave">Leave</button></div></div>
 <div id="workingFields" ${r.status!=="Working Day"?"style='display:none'":""}><div class="field"><label>Daily Duty Notes</label><textarea id="notes" class="textarea" placeholder="What did you do today?">${esc(r.notes)}</textarea><small class="muted" style="font-size:9px">Drafts save automatically. Add short, factual notes.</small></div><div class="field" style="margin-top:12px"><label>Activity Tags</label><div class="tag-list" id="tagList">${tags.map(t=>`<button type="button" class="tag ${(r.tags||[]).includes(t)?"selected":""}" data-tag="${t}">${t}</button>`).join("")}</div></div><div class="form-grid" style="margin-top:12px"><div class="field"><label>AI Tone</label><select id="tone" class="select"><option>Formal</option><option>Concise</option><option>Detailed</option><option>Administrative</option><option>Professional</option></select></div><div class="field" style="align-content:end"><button class="btn primary" id="generate">✦ Generate Professional Report</button></div></div><div class="field" style="margin-top:12px"><label>Generated / Editable Report</label><textarea id="generated" class="textarea" style="min-height:170px" placeholder="Your polished report will appear here…">${esc(r.generatedReport)}</textarea></div><div class="field"><label>Remarks (optional)</label><textarea id="remarks" class="textarea" style="min-height:90px" placeholder="Optional remarks">${esc(r.remarks)}</textarea></div></div>
 <div id="holidayFields" ${r.status!=="Holiday"?"style='display:none'":""}><div class="form-grid"><div class="field"><label>Holiday Name</label><input id="holidayName" class="input" value="${esc(r.holidayName)}" placeholder="Eid-ul-Fitr"></div><div class="field"><label>Description (optional)</label><input id="holidayDescription" class="input" value="${esc(r.holidayDescription)}"></div></div></div>
 <div id="leaveFields" ${r.status!=="Leave"?"style='display:none'":""}><div class="form-grid"><div class="field"><label>Leave Type</label><select id="leaveType" class="select">${["Personal Leave","Medical Leave","Emergency Leave","Casual Leave","Other"].map(x=>`<option ${x===r.leaveType?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>Reason</label><input id="leaveReason" class="input" value="${esc(r.leaveReason)}"></div></div></div>
 <div class="actions" style="justify-content:flex-end"><button class="btn" id="draftSave">Save Draft</button><button class="btn primary" id="saveReport">✓ Save Report</button></div></div></div>`},
 showModal(html){const b=document.getElementById("modalBackdrop"),m=document.getElementById("modal");m.innerHTML=html;b.classList.add("show");this.bindModal();},
 bindModal(){const m=document.getElementById("modal"),close=()=>document.getElementById("modalBackdrop").classList.remove("show");document.getElementById("modalClose").onclick=close;document.getElementById("modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")close()};
 let status=m.querySelector(".statusBtn.primary,.statusBtn.gold,.statusBtn.danger")?.dataset.status||"Working Day";const setStatus=s=>{status=s;m.querySelectorAll(".statusBtn").forEach(b=>{b.className="btn statusBtn "+(b.dataset.status===s?(s==="Holiday"?"gold":s==="Leave"?"danger":"primary"):"")});["workingFields","holidayFields","leaveFields"].forEach(id=>document.getElementById(id).style.display="none");document.getElementById(s==="Working Day"?"workingFields":s==="Holiday"?"holidayFields":"leaveFields").style.display="block"};m.querySelectorAll(".statusBtn").forEach(b=>b.onclick=()=>setStatus(b.dataset.status));
 m.querySelectorAll("[data-tag]").forEach(b=>b.onclick=()=>b.classList.toggle("selected"));
 const draftTimer=()=>{const notes=document.getElementById("notes")?.value||"";if(notes)Store.saveDraft({date:this.selectedDate,notes,status});};document.getElementById("notes")?.addEventListener("input",()=>{clearTimeout(this.draftT);this.draftT=setTimeout(draftTimer,500)});
 document.getElementById("generate")?.addEventListener("click",()=>{const notes=document.getElementById("notes").value.trim();if(!notes)return this.toast("Add some duty notes first.","error");document.getElementById("generated").value=AI.generate(notes,document.getElementById("tone").value);this.toast("Professional report generated.")});
 document.getElementById("draftSave").onclick=()=>{draftTimer();this.toast("Draft saved.")};
 document.getElementById("saveReport").onclick=()=>{const r={date:this.selectedDate,day:dayName(this.selectedDate),status};if(status==="Working Day"){r.notes=document.getElementById("notes").value.trim();r.generatedReport=document.getElementById("generated").value.trim();r.remarks=document.getElementById("remarks").value.trim();r.tags=[...m.querySelectorAll("[data-tag].selected")].map(x=>x.dataset.tag);if(!r.notes&&!r.generatedReport)return this.toast("Please add duty notes.","error");}else if(status==="Holiday"){r.holidayName=document.getElementById("holidayName").value.trim();r.holidayDescription=document.getElementById("holidayDescription").value.trim();if(!r.holidayName)return this.toast("Please enter the holiday name.","error")}else{r.leaveType=document.getElementById("leaveType").value;r.leaveReason=document.getElementById("leaveReason").value.trim();if(!r.leaveReason)return this.toast("Please enter the leave reason.","error")}const result=Store.upsert(r);Store.clearDraft();close();this.toast(result==="created"?"Report saved successfully.":"Report updated successfully.");this.renderView(this.view)}; 
 const d=Store.getDraft();if(d&&d.date===this.selectedDate&&document.getElementById("notes")&&!document.getElementById("notes").value){document.getElementById("notes").value=d.notes;this.toast("Draft restored.")}},
 toast(msg,type){const x=document.createElement("div");x.className="toast";x.textContent=msg;document.getElementById("toastHost").appendChild(x);setTimeout(()=>x.remove(),2600)}
};
document.addEventListener("DOMContentLoaded",()=>App.init());
