const Settings={
 applyTheme(){const s=Store.getSettings();let t=s.theme;if(t==="system")t=matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";document.documentElement.dataset.theme=t},
 saveFromForm(form){const old=Store.getSettings(),f=new FormData(form);const s={...old,name:f.get("name"),designation:f.get("designation"),institution:f.get("institution"),department:f.get("department"),authority:f.get("authority"),email:f.get("email"),phone:f.get("phone"),theme:f.get("theme"),language:f.get("language"),reportStyle:f.get("reportStyle"),showActivities:f.get("showActivities")==="on",showRemarks:f.get("showRemarks")==="on",showSignature:f.get("showSignature")==="on",showPageNumbers:f.get("showPageNumbers")==="on"};Store.saveSettings(s);this.applyTheme();App.renderView("settings");App.toast("Settings saved successfully.")},
 html(){const s=Store.getSettings();return `<div class="page"><div class="page-head"><div><div class="eyebrow">Configuration</div><h1>Settings</h1><p class="page-sub">Personalize your institutional reporting workspace.</p></div></div>
 <form id="settingsForm" class="grid two-col"><div class="section"><div class="section-title"><h3>Personal information</h3></div><div class="form-grid">
 ${this.field("Name","name",s.name)}${this.field("Designation","designation",s.designation)}${this.field("Institution","institution",s.institution)}${this.field("Department","department",s.department)}${this.field("Reporting Authority","authority",s.authority)}${this.field("Email","email",s.email)}${this.field("Phone","phone",s.phone)}
 </div></div><div class="section"><div class="section-title"><h3>Report settings</h3></div>${this.select("Default report style","reportStyle",s.reportStyle,["Formal","Concise","Detailed","Administrative","Professional"])}${this.select("Language","language",s.language,["English","Malayalam","Arabic","Bengali","Urdu"])}
 <div class="grid" style="margin-top:13px;gap:9px">${["showActivities","showRemarks","showSignature","showPageNumbers"].map(k=>`<label class="pill" style="justify-content:space-between"><span>${k.replace("show","Show ")}</span><input type="checkbox" name="${k}" ${s[k]?"checked":""}></label>`).join("")}</div>
 <div style="margin-top:15px"><button class="btn primary" type="submit">Save settings</button></div></div></form>
 <div class="section" style="margin-top:15px"><div class="section-title"><h3>Cloud Data Center</h3><span id="driveStatus">Local only</span></div>
 <div class="notice" style="margin-bottom:13px">Google Drive keeps a private DUTYLOG AI backup so your journal can be restored on another device. LocalStorage remains the fast offline database.</div>
 <div class="form-grid">
  <div class="field"><label>Google OAuth Client ID</label><input class="input" id="googleClientId" placeholder="1234567890-xxxxx.apps.googleusercontent.com" value="${esc(localStorage.getItem("dutylog_google_client_id")||"")}"><small class="muted">Create a Web OAuth client in Google Cloud and enter its client ID here. No secret key belongs in this field.</small></div>
  <div class="field"><label>Automatic backup</label><select class="select" id="autoBackup"><option value="off">Off</option><option value="daily">Daily</option><option value="6h">Every 6 hours</option></select><small class="muted">Backups occur after a successful Drive connection when the app is opened.</small></div>
 </div>
 <div class="actions" style="margin-top:14px"><button class="btn primary" id="connectDrive">Connect Google Drive</button><button class="btn" id="backupDrive">☁ Backup Now</button><button class="btn" id="restoreDrive">↻ Restore / Sync</button><button class="btn" id="disconnectDrive">Disconnect</button></div>
 <div id="driveMeta" class="muted" style="font-size:10px;margin-top:10px"></div></div>
 <div class="section" style="margin-top:15px"><div class="section-title"><h3>Local data & backup</h3></div><div class="actions"><button class="btn" id="exportJson">Export Backup</button><button class="btn" id="importJson">Import Backup</button><button class="btn" id="exportCsv">Export CSV</button><button class="btn danger" id="clearData">Clear All Data</button></div></div></div>`},
 field(label,name,val){return `<div class="field"><label>${label}</label><input class="input" name="${name}" value="${esc(val)}"></div>`},
 select(label,name,val,opts){return `<div class="field" style="margin-bottom:12px"><label>${label}</label><select class="select" name="${name}">${opts.map(o=>`<option ${o===val?"selected":""}>${o}</option>`).join("")}</select></div>`}
};